<?php

/**
 * @file
 */

use Drupal\Core\Url;

/**
 * @file
 * Contains redirect_after_registration.module.
 */

/**
 * Implements hook_form_FORM_alter().
 *
 * Adds method to submit handler to redirect after form submission.
 */
function redirect_after_registration_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_register_form':
      $form['actions']['submit']['#submit'][] = '_redirect_after_registration_user_register_submit';
      break;
  }
}

/**
 * Method to handle redirection.
 */
function _redirect_after_registration_user_register_submit($form, &$form_state) {
  $redirect_destination = \Drupal::config('redirect_after_registration.redirectafterregistrationconfig')->get('destination');
  if (!empty($redirect_destination)) {
    $url = Url::fromUri('internal:' . $redirect_destination);
    $form_state->setRedirectUrl($url);
  }
}
